SELECT  A.AUTHOR_ID, 
        A.AUTHOR_NAME, 
        B.CATEGORY,
        SUM(B.PRICE * S.SALES)  AS TOTAL_SALES
FROM AUTHOR A
        JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
        JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE LEFT(S.SALES_DATE, 7) = "2022-01"
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC