SELECT DISTINCT EEE.ID
FROM (SELECT * FROM ECOLI_DATA WHERE PARENT_ID IS NULL) E 
        JOIN ECOLI_DATA EE ON E.ID = EE.PARENT_ID
        JOIN ECOLI_DATA EEE ON EE.ID = EEE.PARENT_ID
ORDER BY EEE.ID