SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
        LEFT OUTER JOIN ITEM_TREE TT ON T.ITEM_ID=TT.PARENT_ITEM_ID

WHERE TT.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC