SELECT DISTINCT
        O.USER_ID AS USER_ID, 
        O.PRODUCT_ID AS PRODUCT_ID
FROM ONLINE_SALE O JOIN
    (
    SELECT USER_ID, PRODUCT_ID
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING COUNT(*) > 1
    ) OS
    ON O.USER_ID = OS.USER_ID
        AND
        O.PRODUCT_ID = OS.PRODUCT_ID
ORDER BY USER_ID, PRODUCT_ID DESC

