SELECT PRODUCT_CODE, SUM(SALES_AMOUNT * PRICE) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE 
ORDER BY SALES DESC, PRODUCT_CODE

# PRODUCT 
# PRODUCT_ID, PRODUCT_CODE, PRICE
# 상품 ID, 상품코드, 판매가

# OFFLINE_SALE 
# OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
# 오프라인 상품 판매 ID, 상품 ID, 판매량, 판매일