SELECT LEFT(SALES_DATE, 10), PRODUCT_ID, USER_ID,	SALES_AMOUNT
FROM ( SELECT ONLINE_SALE_ID AS SALE_ID,
                USER_ID,
                PRODUCT_ID,	
                SALES_AMOUNT,
                SALES_DATE
        FROM ONLINE_SALE 
        UNION ALL 
        SELECT OFFLINE_SALE_ID AS SALE_ID,	
                NULL AS USER_ID,
                PRODUCT_ID,	
                SALES_AMOUNT,	
                SALES_DATE
        FROM OFFLINE_SALE
      ) a
WHERE LEFT(SALES_DATE, 7) = "2022-03"
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID