SELECT ID, 
        CASE
            WHEN NUM/TOTAL <= 0.25 THEN "CRITICAL"
            WHEN NUM/TOTAL <= 0.5 THEN "HIGH"
            WHEN NUM/TOTAL <= 0.75 THEN "MEDIUM"
            ELSE "LOW"
        END AS COLONY_NAME
FROM (SELECT ID, 
      SIZE_OF_COLONY, 
      ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS NUM, 
      COUNT(*) OVER () AS TOTAL 
      FROM ECOLI_DATA ) a
ORDER BY ID