SELECT U.USER_ID AS USER_ID, 
        U.NICKNAME AS NICKNAME, 
        CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS "전체주소", 
        CONCAT(LEFT(TLNO, 3), "-", SUBSTRING(TLNO,4,4), "-", RIGHT(TLNO, 4)) AS "전화번호"
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID
HAVING COUNT(U.USER_ID) >= 3
ORDER BY U.USER_ID DESC