SELECT P.PRODUCT_ID AS PRODUCT_ID, PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(O.PRODUCE_DATE) = "2022"
        AND MONTH(O.PRODUCE_DATE) = "05"
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID



# FOOD_PRODUCT 
# PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
# 식품 ID, 식품 이름, 식품코드, 식품분류, 식품 가격

# FOOD_ORDER
# ORDER_ID, PRODUCT_ID, AMOUNT, PRODUCE_DATE, IN_DATE, OUT_DATE, FACTORY_ID, WAREHOUSE_ID
# 주문 ID, 제품 ID, 주문량, 생산일자, 입고일자, 출고일자, 공장 ID, 창고 ID