SELECT MEMBER_ID, MEMBER_NAME, GENDER, LEFT(DATE_OF_BIRTH, 10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE SUBSTRING(DATE_OF_BIRTH, 6, 2) = "03"
        AND TLNO IS NOT NULL
        AND GENDER = "W"
ORDER BY MEMBER_ID ASC