SELECT M.MEMBER_NAME, R.REVIEW_TEXT, LEFT(R.REVIEW_DATE, 10)
FROM MEMBER_PROFILE M 
        JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
        JOIN 
        (
            SELECT MEMBER_ID
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(MEMBER_ID) DESC
            LIMIT 1
        ) RR
        ON R.MEMBER_ID = RR.MEMBER_ID



ORDER BY REVIEW_DATE