SELECT T.ITEM_ID AS ITEM_ID, II.ITEM_NAME, II.RARITY
FROM (SELECT * FROM ITEM_INFO WHERE RARITY = "RARE") I JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
               LEFT OUTER JOIN ITEM_INFO II ON T.ITEM_ID = II.ITEM_ID
ORDER BY ITEM_ID DESC