SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) = "8"
        OR MONTH(START_DATE) = "9"
        OR MONTH(START_DATE) = "10"
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
    ) a JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C ON a.CAR_ID = C.CAR_ID
WHERE MONTH(START_DATE) = "8"
        OR MONTH(START_DATE) = "9"
        OR MONTH(START_DATE) = "10"
GROUP BY C.CAR_ID, MONTH(C.START_DATE)
ORDER BY MONTH, CAR_ID DESC