SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (EE.TOP - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA  E JOIN 
        (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS TOP
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)) EE
        ON YEAR(E.DIFFERENTIATION_DATE) = EE.YEAR

ORDER BY YEAR, YEAR_DEV