SELECT I.ID,	
        N.FISH_NAME,	
        I.LENGTH
FROM FISH_NAME_INFO N 
        JOIN FISH_INFO I ON N.FISH_TYPE = I.FISH_TYPE
        JOIN (
            SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
            FROM FISH_INFO
            GROUP BY FISH_TYPE
        ) II ON I.FISH_TYPE = II.FISH_TYPE AND I.LENGTH = II.LENGTH
ORDER BY I.ID