SELECT B.TITLE,	
        B.BOARD_ID,	
        R.REPLY_ID,	
        R.WRITER_ID,	
        R.CONTENTS,	
        LEFT(R.CREATED_DATE, 10)
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE LEFT(B.CREATED_DATE, 7) = "2022-10"
ORDER BY R.CREATED_DATE, B.TITLE