SELECT F.CATEGORY AS CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME AS PRODUCT_NAME
FROM FOOD_PRODUCT F
        INNER JOIN
        (
            SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
            FROM FOOD_PRODUCT
            WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
            GROUP BY CATEGORY
        ) FF
        ON F.PRICE = FF.MAX_PRICE
        AND F.CATEGORY = FF.CATEGORY
ORDER BY MAX_PRICE DESC

